### ISSUE TITLE
Not working on updated site

### ISSUE THREAD

**Issue by alwerhane** [zerocrates/Html5Media#3]
Hello -- we're updating our site from Omeka 1.5.3 running HTML5Media 1.0 to Omeka 2.3 running HTML5Media 2.4 with default settings, and it's not yet working for us (loads video continuously, doesn't resolve).

Here's an example item:
Old site = http://wisconsinuprisingarchive.org/items/show/541
New site = http://dev.wisconsinuprisingarchive.org/items/show/541

Do you have any suggestions for us?  Thank you!

**Comment by zerocrates** [comment]
Did you copy the files over when you copied the site to upgrade it?

Trying to go directly to the non-working video file fails, which generally indicates that the file isn't there: http://dev.wisconsinuprisingarchive.org/files/original/768cce3e41d9156570544334aa32100c.mp4

In particular, remember that the "orignial" files moved from "archive/files" in Omeka 1 to "files/original" in Omeka 2.
