### ISSUE TITLE
Use <audio> tag within metadata?

### ISSUE THREAD

**Issue by jcmundy** [zerocrates/Html5Media#6]
For a project I am trying to include wav files for pronunciations of specific words within the metadata of items and within Exhibits.  I want to keep on html filtering, and that removes the audio tags.  
When I attach the wav files to items as files they are not labeled in any way, which is not helpful for pronunciations. 
Is there any way I can use the HTML5 tags not just for attached files but also in metadata?  Can I use the "file" "title" as a caption for the file on the item page?

**Comment by zerocrates** [comment]
You can't use the HTML5 Media plugin _inside_ metadata fields, it's just totally outside the scope of what the plugin does.

As for fixing your labeling issue by using the File's metadata, you can definitely do something like that. I'm not sure if it makes sense to try to do that in the plugin itself, but it would be something that would make sense (and not be particularly difficult) as a change to your theme.

**Comment by jcmundy** [comment]
Thank you, I did get titles up.
