### ISSUE TITLE
.mov files

### ISSUE THREAD

**Issue by hafizchin** [zerocrates/Html5Media#7]
When uploading .mov files, the player is unable to load / play the file. Instead the following html is displayed:

![image](https://user-images.githubusercontent.com/6478018/54844212-b538df80-4cac-11e9-9373-8c54e02c4e09.png)

**Comment by hafizchin** [comment]
using the latest version of the mediaelement.js resolves the issue.

**Comment by hafizchin** [comment]
Hi,

Is it possible to include the latest release of mediaelement.js to this plugin?

**Comment by zerocrates** [comment]
The library is now updated to the latest version, and the plugin now includes some specific code that should improve .mov support for Chrome.
