### ISSUE TITLE
ZIP file in the views/shared folder since version 2.7

### ISSUE THREAD

**Issue by JBPressac** [zerocrates/Html5Media#8]
Hello,
Something strange: there is a [4.6.16.zip](https://github.com/zerocrates/Html5Media/commit/0e3d94b15bffe182869d57c956d0fd3f86047c95#diff-5228aecefb8e27621c55fa69900e3759) file in the views/shared folder since version 2.7 of the Html5Media plugin.
Thanks,

**Comment by zerocrates** [comment]
Thanks for pointing this out.
